### PR TITLE
Create CNAME file for custom domain

### PR DESCRIPTION
**Pull request by meghan06**
After this is good to go @coolstar can you add the entry in Cloudflare

thanks

### CODE REVIEW

**Comment by ethanaobrien** [comment]
@meghan06 if this will move chrultrabook.github.io/docs/ to just docs.chrultrabook.com, the base url in the vuepress config file needs to be changed

**Comment by meghan06** [comment]
@ethanaobrien what file?

**Comment by ethanaobrien** [comment]
https://github.com/chrultrabook/docs/blob/main/src%2F.vuepress%2Fconfig.js#L10

**Comment by meghan06** [comment]
@ethanaobrien is that fine

**Comment by ethanaobrien** [comment]
Yes

**Comment by ethanaobrien** [comment]
Imo, this should be done via the repo github pages deploy setting, since last I checked it won't redirect chrultrabook.github.io/docs to docs.chrultrabook.com (note that that test was months ago) since this pr will break the current docs link

**Comment by ninelore** [comment]
iirc this will set the github pages setting

**Comment by ninelore** [comment]
> iirc this will set the github pages setting

Could confirm this behavior

**Review by ninelore — APPROVED** [review]

**Comment by ethanaobrien** [comment]
> also this will not break the .github.io

Does it forward requests to .github.io to the custom domain name?

**Comment by ninelore** [comment]
> > also this will not break the .github.io
> 
> Does it forward requests to .github.io to the custom domain name?

yes

**Comment by ethanaobrien** [comment]
Alright, awesome!

**Review by ethanaobrien — APPROVED** [review]

**Pull request merged**
