### PR TITLE
Changing tip about Chromebooks in Dev Mode page

### PR DESCRIPTION
**Pull request by xytrux**
Self Explanatory.

### CODE REVIEW

**Comment by ninelore** [comment]
> Self Explanatory.

no

**Comment by xytrux** [comment]
> > Self Explanatory.
> 
> no.
> 
> Have you read what you wrote there?

Yes I have. And its obvious. I clarified stuff about write protect. If there is no screw, keep the battery out and just plug your Chromebook into the charger. It's even on your docs. Some Chromebooks don't have a write protect screw and the WP is in the battery itself.

**Comment by xytrux** [comment]
Ah wait, nevermind. I realized what I wrote. Im closing this. That is SO wrong. My bad.

**Comment by WeirdTreeThing** [comment]
💀

**Pull request closed without merging**
