### PR TITLE
Make tree happy

### PR DESCRIPTION
**Pull request by ethanaobrien**

### CODE REVIEW

**Comment by WeirdTreeThing** [comment]
finally, good docs

**Review by WeirdTreeThing — DISMISSED** [review]

**Comment by WeirdTreeThing** [comment]
i am sad :( that this has not been merged

**Comment by meghan06** [comment]
@ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien @ethanaobrien 

Pls fix issue

**Comment by ethanaobrien** [comment]
What issue

**Comment by WeirdTreeThing** [comment]
@meghan06 @meghan06 approve the pr

**Review by meghan06 — APPROVED** [review]

**Comment by meghan06** [comment]
@WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing @WeirdTreeThing 

I fixed it for ethan you can go approve and merge now

**Review by WeirdTreeThing — APPROVED** [review]

**Pull request merged**
