### PR TITLE
[unbrick-flipper.md] change unbricked to bricked

### PR DESCRIPTION
**Pull request by player-k12**
change unbricked to bricked as it previously did not make sense

### CODE REVIEW

**Review by ethanaobrien — APPROVED** [review]
lol

**Comment by player-k12** [comment]
yeah

**Comment by player-k12** [comment]
also, the document says the user will not be able to extract the VPD data, but couldn't they read from the chip, put it onto a micro SD card, and then get it on a computer and extract the data, then change the fullrom with the vpd?

**Comment by ethanaobrien** [comment]
Probably. Ask @meghan06 he wrote it

**Review by ninelore — APPROVED** [review]

**Pull request merged**
