### PR TITLE
Update Formatting And Grammar

### PR DESCRIPTION
**Pull request by death7654**
- Replace `*` to `-`
- Remove Contractions (Can't, Won't)
- Remove Whitespaces
- Format Markdown

### CODE REVIEW

**Review by ninelore — CHANGES_REQUESTED** [review]
Lighthouse check needed here aswell

**Comment by ninelore** [comment]
Please take care of remaining markdownlint errors while you are at it

https://github.com/chrultrabook/docs/actions/runs/9871607008/job/27259877199#step:3:1

**Comment by marcsadler** [comment]
What is happening with this PR lol

**Comment by ninelore** [comment]
PRs auto-close when theres no diff from base

**Pull request closed without merging**
