### PR TITLE
Update devices.json

### PR DESCRIPTION
**Pull request by marcsadler**
Please merge after CoolStar updates her list to include MARASOV, otherwise I can revert that commit for now.

### CODE REVIEW

**Comment by marcsadler** [comment]
Would you like me to ask CoolStar directly whether she'll add MARASOV to her list?

**Comment by WeirdTreeThing** [comment]
i dont see why we need to wait for coolstar

**Review by ninelore — APPROVED** [review]
LGTM

**Review by WeirdTreeThing — APPROVED** [review]

**Comment by coolstar** [comment]
Updated my website to also include Marasov. Do ping me next time :)

**Pull request merged**
