### PR TITLE
Picasso eMMC is now supported in edk2

### PR DESCRIPTION
**Pull request by marcsadler**
Thank you @coolstar!

### CODE REVIEW

**Comment by ninelore** [comment]
We should wait until all roms are updated

https://github.com/MrChromebox/scripts/blob/master/sources.sh#L304-L313

**Comment by marcsadler** [comment]
No problem, I thought it was a bit premature too but then I saw CoolStar had already updated her site so I wasn't sure.

**Comment by WeirdTreeThing** [comment]
Yeah wait until 2402 full rom releases, but otherwise looks good to me.

**Comment by CoolPenguin27** [comment]
Seems like the roms are now updated
https://github.com/MrChromebox/scripts/commit/7d279515739da87b95f2b7d7c457f89d403537ea

**Review by ninelore — APPROVED** [review]

**Review by WeirdTreeThing — APPROVED** [review]

**Pull request merged**
