### PR TITLE
Organize / update documentation (re-write)

### PR DESCRIPTION
**Pull request by ethanaobrien**
TODO:

- [x] Organization!!
- [x] a detailed WP removal page should be created
    - [ ] Add photos for screw/jumper methods
- [x] dev mode instructions need to be moved
- [x] newer cros versions need to run sudo in vt2
- [ ] remove spi_intel_platform module to flash internally
- [ ] how to install drivers from a .cab
- [x] 15V USB-C PD requirement for booting without internal battery
- [ ] MDN needs gpu driver to be force installed
- [ ] rwl dualbooting guide
- [ ] explain some common uses for ectool
- [ ] effects of me region when flashing
- [ ] hackintosh roms
- [x] Add more to the home page

### CODE REVIEW

**Comment by marcsadler** [comment]
I noticed that you've removed the relevant terminology section from Getting Started, can I confirm with you that you no longer want to split up the Terminology page into small chunks of relevant terminology on every page?

**Comment by ethanaobrien** [comment]
Yes, it seems a little out of place in some cases and is often something that doesn't actually matter to the user. If a description is needed I just interviewed it into the instructions themselves (like with suzyq on the flashing custom firmware page)

**Comment by marcsadler** [comment]
Okay great, thanks! I'll amend the edits I've done towards this so far. 

My commits focuses on editing markdown layout and cleaning up formatting, is that still relevant in light of the big overhaul of the docs that you're working on? I'm happy to discard my changes for now, or I could open a PR on your fork instead of upstream docs like what CoolPenguin27 has done.

**Comment by ethanaobrien** [comment]
>My commits focus on editing markdown layout and cleaning up formatting, is that still relevant in light of the big overhaul of the docs that you're working on?

Most of what's being done in this re-write is organization and clarification, but that too is important. As you can see the first couple of pages here have been re-written already (https://cb-docs-demo.netlify.app/docs/)

>I'm happy to discard my changes for now, or I could open a PR on your fork instead of upstream docs like what CoolPenguin27 has done.

You're welcome to open a pr on my fork, and I'd be really glad if you could do so.

**Comment by ethanaobrien** [comment]
See #106

**Pull request closed without merging**
