### PR TITLE
08.2023 rewrite

### PR DESCRIPTION
**Pull request by meghan06**
TODO List:

**From TODO.txt**
  - [x] Fix broken Jumper links in supported devices chart
  - [x] Update macOS Post-Install to include fixing NVRAM on 10th gen devices (DevirtualizeMimo)
  - [x] Organize guide by sections, i.e firmware pages go together in a group and whatnot
  - [x] Make some FAQ questions (the long ones) easier to comprehend 
  - [x] Known Issues -> OS -> Linux add workaround for Broken USB-C on TigerLake and AlderLake
  - [ ] Update Terminology page to include newer CPU generations 
  - [x] Flashing Custom Firmware -> Step 2, include SuzyQ CCD as one of the possible methods
  - [x] Flashing Custom Firmware -> Updating coreboot, make instructions more instructionaly
  - [x] altOS -> Windows, specify that drivers are paid for SKL and newer only
  - [x] Add SOF/AVS sleep wake crash to known issues
  - [ ] Update discounted CPUs in Windows and CSDriver page
  - [x] Note that PopOS and Debian 12 need custom kernel 
  - [ ] Post Install, add custom kernel reference (see #12)
  
**Others:**
  - [ ] there is a lot of jumping around and following links, this should really be more linear
  - [ ] there is some unnecessary details in certain sections that can cause confusion, maybe these would be better if we made a  section for a more detailed explanation
  - [ ] certain processes like dev mode could be explained better
  - [ ] change the order of steps and pages to be more linear (prerequisites, terminology, firmware explanation should go before any actual steps, then dev mode instructions next, then find system info, supported devices, flash fw, etc) the order will need more discussion
  - [ ] move all WP instructions to a new page, then link to that in supported devices
  - [ ] remove and reword certain sections/lines to be easier to understand all over the docs
  - [ ] explain the steps of the firmware util a little better
  - [ ] explain dev mode instructions mode, mention that you need to press ctrl + d every time you see os verification/dev mode screen
  - [ ] move updating coreboot to a new page, the current page doesn't make sense
  - [ ] give some tips for disassembling a device for people who haven't done it before
  - [x] move the linux compatibility spreadsheet to the docs **(NEEDS WORK)**
  - [ ] explain keyd steps better (this really should be automated, I just need to figure out how to do that)
  - [ ] not all terminology is relevant to everyone, move the terminology relevant to each page to the top and remove the terminology page
  - [ ] create a page describing each platform/generation for OS/firmware support (linux support sheet could go here)
  
Other cool ideas:
- [ ] expand the ventoy page to be for general bootable drive creation
- [ ] explain that you should copy a code block exactly as is into the terminal (ctrl + shift + v is how you paste in a terminal)

### CODE REVIEW

**Comment by ninelore** [comment]
It should be mentioned too that the USB-C is not always broken has a chance to work ootb

**Comment by ninelore** [comment]
About Streamlining: 

We really shouldn't turn documentation into a step-by-step guide. 

Keep Pages for one topic each and maybe add a step-by-step guide as a seperate page.

**Comment by meghan06** [comment]
> It should be mentioned too that the USB-C is not always broken has a chance to work ootb

Alright.

> We really shouldn't turn documentation into a step-by-step guide.

Some portions of the doc has to be step by step (i.e flashing firmware). If we keep pages for one topic each and maybe add a step-by-step guide as a seperate page, that'd be an insane amount of work and would probably require an entire rewrite.

**Comment by meghan06** [comment]
shut up spellbot. im deleting this thing.

**Pull request merged**
