### PR TITLE
Organize / update documentation (re-write)

### PR DESCRIPTION
**Pull request by ethanaobrien**
(Originally #103, no changes were made between the two)
TODO:

- [x] Organization!!
- [x] a detailed WP removal page should be created
    - [ ] Add photos for screw/jumper methods
- [x] dev mode instructions need to be moved
- [x] newer cros versions need to run sudo in vt2
- [ ] remove spi_intel_platform module to flash internally
- [x] how to install drivers from a .cab
- [x] 15V USB-C PD requirement for booting without internal battery
- [ ] MDN needs gpu driver to be force installed
- [ ] rwl dualbooting guide
- [x] explain some common uses for ectool
- [ ] effects of me region when flashing
- [x] hackintosh roms
- [x] Add more to the home page
- [x] Supported devices search

### CODE REVIEW

**Review by ninelore — CHANGES_REQUESTED** [review]
- This should be documentation, not a guide. Avoid latter word and keep that in mind for further content adjustments down the line (guide flow vs. wiki-like topic-based  structure)
- We should cut down further on the content around paid proprietary drivers because of the feedback elly told us about. In paticular the related FAQ questions should be moved to coolstar.org IMHO (@coolstar  FYI)

**Comment by WeirdTreeThing** [comment]
Adding on to what ninelore said, we should include more technical details before merging this.

**Comment by ninelore** [comment]
After further reading: The order and content of the documentation is still a mess. I wanna emphasize again that we should turn the docs more into a wiki

**Comment by ethanaobrien** [comment]
> This should be documentation, not a guide. Avoid latter word and keep that in mind for further content adjustments down the line (guide flow vs. wiki-like topic-based structure)

How should a wiki be formatted?

> We should cut down further on the content around paid proprietary drivers because of the feedback elly told us about. In paticular the related FAQ questions should be moved to coolstar.org IMHO

What else should I cut down? The only thing I have left is what drivers you need to buy, should that be removed?


> Adding on to what ninelore said, we should include more technical details before merging this.

I think the more technical information should be in smaller pr's after merging, making them easier to review and so I don't need to rebase every time the main branch is updated in the meantime

**Comment by actuallyarm64** [comment]
> Adding on to what ninelore said, we should include more technical details before merging this.

its best to keep the PR focused and manageable. technical details can be added in later updates. keeps everything more organized.

**Comment by actuallyarm64** [comment]
Where do you want the .cab to driver guide on?

Also, i suggest you remove the /docs directory. its pretty useless.

**Comment by ethanaobrien** [comment]
>Also, i suggest you remove the /docs directory. its pretty useless

Organization. Since .vuepress/public serves at root

**Review by ninelore — DISMISSED** [review]

**Review by death7654 — APPROVED** [review]
This is pretty good, follows a wiki-like and guide like documentation, It is well made

**Comment by WeirdTreeThing** [comment]
I think the enrolled warning should be the first thing you see right after clicking get started, instead of on the dev mode page.

**Comment by ethanaobrien** [comment]
> I think the enrolled warning should be the first thing you see right after clicking get started, instead of on the dev mode page.

Moved

**Review by ninelore — APPROVED** [review]

**Review by WeirdTreeThing — APPROVED** [review]

**Comment by actuallyarm64** [comment]
lets goo it got merged

**Pull request merged**
