### PR TITLE
security vuln fix, grammar + clarification

### PR DESCRIPTION
**Pull request by dj1ch**
npm returned a security vulnerability, had to bump `vite` to `4.5.2`(hence the changes to `package-lock.json`) plus i fixed some grammar to `index.md`, `template.md`(template for supported devices), and `faq.md`. mentioned the security vuln fix(es) with the line i added in `contributing.md`

screenshot:

Desktop Screenshot 2024 01 28 - 11 00 35 14

### CODE REVIEW

**Review by ethanaobrien — COMMENTED** [review]
Don't know how I feel about adding this to the instructions when building/running. Npm warns itself that this can break dependencies, and it's never a good idea to manually update a dependencies dependency.

You should attempt upgrading vuepress to `2.0.0-rc.2` first, instead of updating a sub-depenency. This may break things, make sure it works before pushing.

https://www.npmjs.com/package/vuepress/?activeTab=versions

**Comment by WeirdTreeThing** [comment]
web dev moment

**Comment by dj1ch** [comment]
> Don't know how I feel about adding this to the instructions when building/running. Npm warns itself that this can break dependencies, and it's never a good idea to manually update a dependencies dependency.
> 
> You should attempt upgrading vuepress to `2.0.0-rc.2` first, instead of updating a sub-depenency. This may break things, make sure it works before pushing.
> 
> https://www.npmjs.com/package/vuepress/?activeTab=versions

so do we update the versions through the `package-lock.json`? i think you guys can edit the commits right?

**Comment by ethanaobrien** [comment]
> web dev moment

There's nothing different about this than any other programming language.

>so do we update the versions through the package-lock.json?

Avoid editing package-lock.json. edit package.json

>i think you guys can edit the commits right?

`git reset HEAD~1 && git push -f` will undo your commit.

For the future, please submit different patches in different prs, it helps with reviewing and merging

**Comment by WeirdTreeThing** [comment]
> There's nothing different about this than any other programming language.

js devs coping is funny

**Comment by dj1ch** [comment]
> > web dev moment
> 
> There's nothing different about this than any other programming language.
> 
> > so do we update the versions through the package-lock.json?
> 
> Avoid editing package-lock.json. edit package.json
> 
> > i think you guys can edit the commits right?
> 
> `git reset HEAD~1 && git push -f` will undo your commit.
> 
> For the future, please submit different patches in different prs, it helps with reviewing and merging

gotcha

**Comment by dj1ch** [comment]
> > There's nothing different about this than any other programming language.
> 
> js devs coping is funny

😭😭😭

**Comment by ninelore** [comment]
yea package-lock editing is really bad practice

**Comment by dj1ch** [comment]
@ethanaobrien do i just open up a seperate pr?

**Comment by ethanaobrien** [comment]
Yes, one for rewording/grammar, one for the security issue

**Comment by MilkyDeveloper** [comment]
image

🤡🤡🤡

**Comment by WeirdTreeThing** [comment]
wrong repo

**Comment by dj1ch** [comment]
> image
> 
> 🤡🤡🤡

holy sh*t its milky

**Pull request closed without merging**
